version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - cd /root
      - mkdir -p onnxruntime/python pillow/python transformers/python
      - python3 -m pip install --user pip --upgrade
      - python3 -m pip install --user virtualenv
      - python3 -m virtualenv OnnxRuntime
      - source OnnxRuntime/bin/activate

artifacts:
  name: onnxruntime
  base-directory: /root/onnxruntime
  files:
    - '**/*'
  discard-paths: no
  secondary-artifacts:
    pillow:
      base-directory: /root/pillow
      files:
        - '**/*'
      discard-paths: no
    transformers:
      base-directory: /root/transformers
      files:
        - '**/*'
      discard-paths: no
